# Generated by Django 4.2.7 on 2023-11-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_school', '0003_rename_id_pupiles_individual_training_pupiles_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_training',
            old_name='pupiles_id',
            new_name='id_pupiles',
        ),
        migrations.RenameField(
            model_name='individual_training',
            old_name='trainer_id',
            new_name='id_trainer',
        ),
    ]
