# Generated by Django 4.2.7 on 2023-11-12 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id_trainer', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID тренера')),
                ('first_name', models.TextField(verbose_name='Фамилия')),
                ('second_name', models.TextField(verbose_name='Имя')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('id_passport', models.IntegerField(verbose_name='Номер и серия паспорта')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('job', models.TextField(verbose_name='Специальность')),
                ('degree', models.TextField(verbose_name='Разряд')),
                ('date_entrance', models.DateField(verbose_name='Дата приема на работу')),
                ('date_didmissal', models.DateField(blank=True, null=True, verbose_name='Дата уволнения')),
                ('experience', models.SmallIntegerField(blank=True, null=True, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Тренеры',
                'verbose_name_plural': 'Тренеры',
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_groups', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID группы')),
                ('type_sport', models.TextField(verbose_name='Вид спорта')),
                ('age_group', models.SmallIntegerField(verbose_name='Минимальный возраст для группы')),
                ('name_group', models.TextField(verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Pupiles',
            fields=[
                ('id_pupiles', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID воспитанника')),
                ('first_name', models.TextField(verbose_name='Фамилия')),
                ('second_name', models.TextField(verbose_name='Имя')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('id_passport', models.IntegerField(blank=True, null=True, verbose_name='Номер и серия паспорта')),
                ('gender', models.CharField(choices=[('W', 'Женский'), ('M', 'Мужской')], verbose_name='Пол')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('date_entrance', models.DateField(verbose_name='Дата поступления')),
                ('date_didmissal', models.DateField(blank=True, null=True, verbose_name='Дата отчисления')),
                ('degree', models.TextField(blank=True, null=True, verbose_name='Разряд')),
                ('id_groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sport_school.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Воспитанники',
                'verbose_name_plural': 'Воспитанники',
                'db_table': 'pupiles',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id_pay', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID платежа')),
                ('date_pay', models.DateField(verbose_name='Дата платежа')),
                ('date_nextPay', models.DateField(verbose_name='Дата следующего платежа')),
                ('check_pay', models.BinaryField(verbose_name='Статус платежа')),
                ('id_pupiles', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.pupiles', verbose_name='ID воспитанника')),
            ],
            options={
                'verbose_name': 'Платежи',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Individual_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_day', models.DateTimeField(verbose_name='Дата тренировки')),
                ('type_training', models.TextField(verbose_name='Тип тренировки')),
                ('id_pupiles', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.pupiles', verbose_name='ID воспитанника')),
                ('id_trainer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.coach', verbose_name='ID тренера')),
            ],
            options={
                'verbose_name': 'Индивидуальные треннировки',
                'verbose_name_plural': 'Индивидуальные треннировки',
                'db_table': 'individual_training',
            },
        ),
        migrations.CreateModel(
            name='Groups_Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_day', models.DateTimeField(verbose_name='Дата тренировки')),
                ('type_training', models.TextField(verbose_name='Тип тренировки')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.groups', verbose_name='Группы')),
                ('id_trainer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.coach', verbose_name='ID тренера')),
            ],
            options={
                'verbose_name': 'Групповые треннировки',
                'verbose_name_plural': 'Групповые треннировки',
                'db_table': 'groups_training',
            },
        ),
    ]
