# Generated by Django 4.2.7 on 2023-11-12 20:30

from django.db import migrations, models
import django.db.models.deletion
import sport_school.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups_training',
            name='id_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='groups_training',
            name='id_trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sport_school.coach', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='groups_training',
            name='training_day',
            field=models.DateTimeField(verbose_name='Дата и время тренировки'),
        ),
        migrations.AlterField(
            model_name='pupiles',
            name='id_pupiles',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[sport_school.models.valid_pupiles_id], verbose_name='ID воспитанника'),
        ),
        migrations.AlterField(
            model_name='pupiles',
            name='phone_number',
            field=models.TextField(validators=[sport_school.models.validate_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
