# Generated by Django 4.2.7 on 2023-11-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_school', '0002_alter_groups_training_id_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_training',
            old_name='id_pupiles',
            new_name='pupiles_id',
        ),
        migrations.RenameField(
            model_name='individual_training',
            old_name='id_trainer',
            new_name='trainer_id',
        ),
    ]
